### PR TITLE
Fix items being set asynchronously or initialised as falsy values 

### LINKED ISSUE #1: Unable to verify items identifier in api calls
## Description
When you fetch for items in a api call, it throws an error `Please, make sure to provide a valid identifier`
I was searching about it, and I noticed it's because when the application loads the items are an empty array, so the library cannot find the `id`

Great library by the way @LauraBeatris! 

## How to Reproduce
Access : [this sandbox](https://codesandbox.io/s/experimeting-use-selected-items-hook-7z168?file=/src/App.tsx)

## Package version
1.0.6

## Node version
12.18.2

## React Version
16.12.0

### PR DESCRIPTION
**Pull request by LauraBeatris**
## Implementation Details 

Refer to #1 

### Now there are two effects that handle the initialization of the items 

1. Checks if the identifier is invalid **only** if the items array has at least one item.
```
useEffect(() => {
    const itemIdentifierIsInvalid = !(items?.find(findItem => (
      findItem[itemIdentifier]
    )));

    const hasItems = !!items?.length;

    if (itemIdentifierIsInvalid && hasItems) {
      throw new Error("Please, make sure to provide a valid identifier");
    }
  }, [
    itemIdentifier,
    items,
  ]);
```

2. Generate an updated items list with the ``selected`` state, according to its changes. 
An empty array will be set if it hasn't a value yet, for instance: ``undefined`` or ``null``, 
maybe because it's being set asynchronously. 
```
 useEffect(() => {
    let updatedItemsList: Item<T>[] = [];

    if (items) {
      updatedItemsList = items.map(listItem => {
        const isSelected = !!(selectedItems.find(selectedItem => (
          selectedItem[itemIdentifier] === listItem[itemIdentifier]
        )));

        return {
          ...listItem,
          selected: isSelected,
        };
      });
    }

    setItemsList(updatedItemsList);
  }, [
    selectedItems,
    itemIdentifier,
    items,
  ]);
```

### CODE REVIEW

File: use-selected-items-hook/src/useSelectedItems.ts [hunk 1]
```diff
@@ -1,34 +1,53 @@
...
+  useEffect(() => {
+    const itemIdentifierIsInvalid = !(items?.find(findItem => (
       findItem[itemIdentifier]
     )));
 
-    if (!identifierIsValid) {
+    const hasItems = !!items?.length;
+
+    if (itemIdentifierIsInvalid && hasItems) {
       throw new Error("Please, make sure to provide a valid identifier");
```
Comment (pedro-lb) [inline use-selected-items-hook/src/useSelectedItems.ts]: Probably better to use `invariant` instead of `if (...) { throw new Error(...) }`.

Check it out here: https://www.npmjs.com/package/invariant

Also, note that the condition is inverted (if `false`, it throws).

So:

```jsx
if (itemIdentifierIsInvalid && hasItems) {
      throw new Error("Please, make sure to provide a valid identifier");
}
```

Becomes (adding `hasItems` to `itemIdentifierIsInvalid` eval):

Note: please validate expression below!

```jsx
const isValid = !items?.length || (
  !!(items?.find(findItem => (
    findItem[itemIdentifier]
  )))
);

invariant(isValid, "Please, make sure to provide a valid identifier");
```

Comment (LauraBeatris) [reply use-selected-items-hook/src/useSelectedItems.ts]: Should I add some babel plugin in order to minify these errors in the production environment?

Refer to: https://github.com/zertosh/invariant/issues/36#issuecomment-406933188

Comment (LauraBeatris) [reply use-selected-items-hook/src/useSelectedItems.ts]: Applied in 4b71eed6e9a1d00ddb28f886d0f0b09a922c674e
